---

- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: apt update
      apt:
        update_cache: true

- name: Configuring HAproxy loadbalancer
  hosts: HAproxy
  become: true
  tasks:

    - name: Installing HAproxy
      apt:
        name: haproxy
        state: present
        update_cache: true
      

    - name: gather server ip addresses
      setup:
            filter: ansible_default_ipv4.address     
         
    
    - name: copy files haproxy.cfg
      template:
        src: haproxy.cfg.j2
        dest: "/etc/haproxy/haproxy.cfg"
      notify:
        - restart haproxy
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: true
    - name: Copy Nginx configuration for UDP load balancing
      template:
        src: nginx_udp_load_balancer.conf.j2
        dest: /etc/nginx/conf.d/udp_load_balancer.conf
      notify:
        - restart nginx

  handlers:

    - name: restart haproxy
      service:
       name: haproxy
       state: restarted

    - name: restart nginx
      service:
        name: nginx
        state: restarted
    
    - name: restart snmpd
      service:
        name: snmpd
        state: restarted


- hosts: webservers
  become: true
  tasks:
    - name: install pip
      apt:
        name: python3-pip
        state: present
    
    - name: install flask
      pip:
        executable: pip3
        name: flask
        state: latest
    - name: install gunicorn
      pip:
        executable: pip3
        name: gunicorn
        state: latest

    - name: createnew directory
      file:
              path: "/home/flask-app/"
              state: directory
    - name: copy app.py to webservers
      template:
        src: "application2.py"
        dest: "/home/flask-app/app.py"


    - name: start flask app
      shell: |
        cd /home/flask-app/
        gunicorn --bind 0.0.0.0:80 app:app&  
    
    - name: snmpd
      apt:
        name: snmpd
        state: present
        update_cache: true
    - name: copy snmpd.conf
      template:
        src: snmpd.conf.j2
        dest: "/etc/snmp/snmpd.conf"
      notify:
        - restart snmpd


